#
# PX4 bootloader build rules for STM32F0 targets.
#

# 5 seconds / 5000 ms default delay
PX4_BOOTLOADER_DELAY	?= 5000

SRCS		 = $(COMMON_SRCS) main_f0.c

FLAGS		+= -mlittle-endian -mcpu=cortex-m0 -march=armv6-m -mthumb\
       -DTARGET_HW_$(TARGET_HW) \
       -DSTM32F0 \
		   -T$(LINKER_FILE) \
		   -L$(LIBOPENCM3)/lib \
		   -lopencm3_stm32f0

#
# General rules for making dependency and object files
# This is where the compiler is called
#
include rules.mk
