name: Build and Deploy

on:
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write


jobs:
  coverage:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential wget astyle
      - name: Get toolchain
        run: |
            wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
            tar -jxf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
            echo "$(pwd)/gcc-arm-none-eabi-9-2020-q2-update/bin" >> $GITHUB_PATH
      - name: Build
        run: make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: px4-bootloader-binaries
          path: |
            build/*/*.bin
            build/*/*.elf
            build/*/*.hex

      - name: Check style
        run: make check_format

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
          files: |
            build/*/*.bin
            build/*/*.elf
            build/*/*.hex
